package org.jboss.shrinkwrap.descriptor.metadata.codegen;

import java.util.ArrayList;
import java.util.List;

import org.jboss.shrinkwrap.descriptor.metadata.MetadataElement;
import org.jboss.shrinkwrap.descriptor.metadata.MetadataItem;

import com.sun.codemodel.JDefinedClass;

public class AttributeBuilder {

    private static final String[] SEARCH_LIST = new String[] { "DATATYPE", "ELEMENTNAME_P", "ELEMENTNAME_C", "CLASSNAME_P" };

    private static final String GET_WITH_DATATYPE = "\n"
        + "    /**\n"
        + "     * Returns the <code>ELEMENTNAME_C</code> attribute\n"
        + "     * @return the value defined for the attribute <code>ELEMENTNAME_C</code>\n"
        + "     */\n"
        + "    public DATATYPE getELEMENTNAME_P() {\n"
        + "        if (getNode().getAttribute(\"ELEMENTNAME_C\") != null && !getNode().getAttribute(\"ELEMENTNAME_C\").equals(\"null\")) {\n"
        + "            return DATATYPE.valueOf(getNode().getAttribute(\"ELEMENTNAME_C\"));\n"
        + "        }\n"
        + "        return null;\n"
        + "    }\n";

    private static final String GET_WITH_BOOLEAN = "\n"
        + "    /**\n"
        + "     * Returns the <code>ELEMENTNAME_C</code> attribute\n"
        + "     * @return the value defined for the attribute <code>ELEMENTNAME_C</code>\n"
        + "     */\n"
        + "    public Boolean isELEMENTNAME_P() {\n"
        + "        return org.jboss.shrinkwrap.descriptor.impl.base.Strings.isTrue(getNode().getAttribute(\"ELEMENTNAME_C\"));\n"
        + "    }\n";

    private static final String GET_WITH_STRING = "\n"
        + "    /**\n"
        + "     * Returns the <code>name</code> attribute\n"
        + "     * @return the value defined for the attribute <code>ELEMENTNAME_C</code>\n"
        + "     */\n"
        + "    public String getELEMENTNAME_P() {\n"
        + "        return getNode().getAttribute(\"ELEMENTNAME_C\");\n"
        + "    }\n";

    private static final String SET_WITH_DATATYPE = "\n"
        + "    /**\n"
        + "     * Sets the <code>ELEMENTNAME_C</code> attribute\n"
        + "     * @param ELEMENTNAME_C the value for the attribute <code>ELEMENTNAME_C</code>\n"
        + "     * @return the current instance of <code>CLASSNAME_P</code>\n"
        + "     */\n"
        + "    public CLASSNAME_P ELEMENTNAME_C(DATATYPE ELEMENTNAME_C) {\n"
        + "        getNode().attribute(\"ELEMENTNAME_C\", ELEMENTNAME_C);\n"
        + "        return this;\n"
        + "    }\n";

    private static final String REM_WITH_DATATYPE = "\n"
        + "    /**\n"
        + "     * Removes the <code>ELEMENTNAME_C</code> attribute\n"
        + "     * @return the current instance of <code>CLASSNAME_P</code>\n"
        + "     */\n"
        + "    public CLASSNAME_P removeELEMENTNAME_P() {\n"
        + "        getNode().removeAttribute(\"ELEMENTNAME_C\");\n"
        + "        return this;\n"
        + "    }\n";

    private static final String[] METHOD_LIST_INTEGER = new String[] {
        GET_WITH_DATATYPE,
        SET_WITH_DATATYPE,
        REM_WITH_DATATYPE,
    };

    private static final String[] METHOD_LIST_BOOLEAN = new String[] {
        GET_WITH_BOOLEAN,
        SET_WITH_DATATYPE,
        REM_WITH_DATATYPE,
    };

    private static final String[] METHOD_LIST_STRING = new String[] {
        GET_WITH_STRING,
        SET_WITH_DATATYPE,
        REM_WITH_DATATYPE,
    };

    public static void addAttributeMethods(final JDefinedClass clazz, final MetadataElement element, final String className, final boolean isApi) throws Exception {
        generateImpl(clazz, className, element, isApi);
    }

    //-----------------------------------------------------------------------||
    //--Private Methods -----------------------------------------------------||
    //-----------------------------------------------------------------------||

    private static void generateImpl(final JDefinedClass clazz, final String className, final MetadataElement element, final boolean isApi) throws Exception {
        if (element.getIsAttribute()) {
            final String elementName = BuilderUtil.checkReservedWords(CodeGen.getCamelCase(element.getName()));
            final Class<?> dataType = BuilderUtil.getDataType(element.getType());
            final String[] replaceList = getReplaceList(dataType, className, elementName);
            clazz.direct(element.asClassComment());
            clazz.direct("    // generated by AttributeBuilder: " + dataType);
            if (dataType == Integer.class) {
                for (String methodBody : METHOD_LIST_INTEGER) {
                    clazz.direct(BuilderUtil.replaceAll(methodBody, isApi, SEARCH_LIST, replaceList));
                }
            } else if (dataType == Boolean.class) {
                for (String methodBody : METHOD_LIST_BOOLEAN) {
                    clazz.direct(BuilderUtil.replaceAll(methodBody, isApi, SEARCH_LIST, replaceList));
                }
            } else {
                for (String methodBody : METHOD_LIST_STRING) {
                    clazz.direct(BuilderUtil.replaceAll(methodBody, isApi, SEARCH_LIST, replaceList));
                }
            }
        }
    }

    private static String[] getReplaceList(final Class<?> dataType, final String className, final String elementName) {
        return new String[] {dataType.getSimpleName(), CodeGen.getPascalizeCase(elementName), elementName, className};
    }

}
